### ISSUE TITLE
Broken links for data download

### ISSUE THREAD

**Issue by marcoCalipari** [zqzqz/AdvCollaborativePerception#2]
### Problem description

When running `script/download.sh` the code returns an error saying that downloading is impossible. With manual inspection, via the provided link, google drive reports a 404 error for the following URL: https://drive.google.com/file/d/1fuYK-oNA0FpZtT8rUiEETOCNmtO3FCfS/view?usp=sharing

Unfortunately this is the last link that is necessary for the code execution.

**Comment by zqzqz** [comment]
Thank you for pointing this out. We actually use the OPV2V test.zip data (whose introduction is [link](https://opencood.readthedocs.io/en/latest/md_files/data_intro.html)). It seems the original link is broken. I would try to upload a copy of my local data to fix it asap.

**Comment by marcoCalipari** [comment]
I imagined, thanks for the quick response!

**Comment by zqzqz** [comment]
Sorry for the delay. I uploaded  data to a new link: https://drive.google.com/file/d/11JdX113eVs6wtCS0c5j7L6KfQcJQn2h0/view?usp=sharing
Unlike the original OPV2V data, it excludes camera images which are not used by this repo anyway.

**Comment by marcoCalipari** [comment]
Thanks a lot for the new link. 
Did you use the link directly from the OpenCOOD data preparation page? (https://opencood.readthedocs.io/en/latest/md_files/data_intro.html)

I will try now the new link, best

**Comment by marcoCalipari** [comment]
The link downloads, thanks
